import {
  ActivityIcon,
  AlertTriangleIcon,
  ArchiveIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  BadgeCheckIcon,
  BanIcon,
  BarChart3Icon,
  BellIcon,
  BookOpenIcon,
  BookmarkIcon,
  BotIcon,
  BoxIcon,
  BrainIcon,
  Building2Icon,
  CalculatorIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleDotIcon,
  CircleHelpIcon,
  CircleIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  Clock3Icon,
  CloudOffIcon,
  CloudUploadIcon,
  Code2Icon,
  ConstructionIcon,
  CpuIcon,
  CrosshairIcon,
  DownloadIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FilePlus2Icon,
  FileTextIcon,
  FlameIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderXIcon,
  GavelIcon,
  GiftIcon,
  GraduationCapIcon,
  Grid2x2Icon,
  HeadphonesIcon,
  HeartPulseIcon,
  HelpCircleIcon,
  HistoryIcon,
  HomeIcon,
  HourglassIcon,
  ImageIcon,
  InfoIcon,
  KeyRoundIcon,
  LayoutDashboardIcon,
  LayoutGridIcon,
  LightbulbIcon,
  LinkIcon,
  ListChecksIcon,
  Loader2Icon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  MailIcon,
  MapPinIcon,
  Maximize2Icon,
  MenuIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MicIcon,
  MoonIcon,
  MoreVerticalIcon,
  MoveIcon,
  PaletteIcon,
  PauseIcon,
  PencilIcon,
  PencilLineIcon,
  PersonStandingIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  QuoteIcon,
  RadioIcon,
  RefreshCwIcon,
  RepeatIcon,
  RocketIcon,
  RouteIcon,
  SaveIcon,
  SchoolIcon,
  SearchIcon,
  SearchXIcon,
  SendIcon,
  SettingsIcon,
  Settings2Icon,
  Share2Icon,
  ShieldCheckIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SparklesIcon,
  SquareIcon,
  StarIcon,
  SunIcon,
  TargetIcon,
  TerminalIcon,
  ThumbsUpIcon,
  TimerIcon,
  Trash2Icon,
  TrendingUpIcon,
  TrophyIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  VerifiedIcon,
  Volume2Icon,
  WandSparklesIcon,
  WorkflowIcon,
  WrenchIcon,
  XIcon,
  ZapIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/** Material Symbols ligature → Lucide icon (hard cutover map). */
const MATERIAL_TO_LUCIDE = {
  account_balance: Building2Icon,
  account_tree: WorkflowIcon,
  add: PlusIcon,
  add_circle: PlusCircleIcon,
  admin_panel_settings: Settings2Icon,
  all_inclusive: RepeatIcon,
  analytics: BarChart3Icon,
  architecture: BoxIcon,
  arrow_back: ArrowLeftIcon,
  arrow_forward: ArrowRightIcon,
  arrow_outward: ArrowUpRightIcon,
  arrow_upward: ArrowUpIcon,
  auto_awesome: SparklesIcon,
  auto_stories: BookOpenIcon,
  bar_chart: BarChart3Icon,
  biotech: MicIcon,
  bolt: ZapIcon,
  calculate: CalculatorIcon,
  calendar_month: CalendarDaysIcon,
  calendar_today: CalendarIcon,
  check: CheckIcon,
  check_circle: CheckCircle2Icon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  child_care: PersonStandingIcon,
  close: XIcon,
  cloud_off: CloudOffIcon,
  cloud_upload: CloudUploadIcon,
  code: Code2Icon,
  compare_arrows: Share2Icon,
  construction: ConstructionIcon,
  dark_mode: MoonIcon,
  dashboard: LayoutDashboardIcon,
  delete: Trash2Icon,
  download: DownloadIcon,
  deployed_code: BoxIcon,
  description: FileTextIcon,
  drive_file_move: MoveIcon,
  edit: PencilIcon,
  edit_note: PencilLineIcon,
  emoji_events: TrophyIcon,
  emoji_objects: LightbulbIcon,
  engineering: WrenchIcon,
  error: AlertTriangleIcon,
  event_note: ClipboardListIcon,
  expand_more: ChevronDownIcon,
  fact_check: ClipboardCheckIcon,
  flash_on: ZapIcon,
  folder: FolderIcon,
  folder_off: FolderXIcon,
  folder_open: FolderOpenIcon,
  format_quote: QuoteIcon,
  forum: MessageSquareIcon,
  forward_10: SkipForwardIcon,
  foundation: Building2Icon,
  gavel: GavelIcon,
  graphic_eq: ActivityIcon,
  grid_view: Grid2x2Icon,
  groups: UsersIcon,
  headphones: HeadphonesIcon,
  help_outline: HelpCircleIcon,
  history: HistoryIcon,
  home: HomeIcon,
  hourglass_empty: HourglassIcon,
  hourglass_top: HourglassIcon,
  image: ImageIcon,
  info: InfoIcon,
  light_mode: SunIcon,
  lightbulb: LightbulbIcon,
  lightbulb_circle: LightbulbIcon,
  link: LinkIcon,
  local_fire_department: FlameIcon,
  lock: LockIcon,
  login: LogInIcon,
  logout: LogOutIcon,
  mail: MailIcon,
  medical_services: HeartPulseIcon,
  menu: MenuIcon,
  menu_book: BookOpenIcon,
  military_tech: TrophyIcon,
  note_add: FilePlus2Icon,
  notifications: BellIcon,
  open_in_new: ExternalLinkIcon,
  palette: PaletteIcon,
  pause: PauseIcon,
  pending: Loader2Icon,
  person: UserIcon,
  picture_as_pdf: FileTextIcon,
  place: MapPinIcon,
  play_arrow: PlayIcon,
  play_circle: PlayCircleIcon,
  podcasts: HeadphonesIcon,
  priority_high: AlertTriangleIcon,
  progress_activity: Loader2Icon,
  psychology: BrainIcon,
  quiz: CircleHelpIcon,
  radio_button_checked: CircleDotIcon,
  radio_button_unchecked: CircleIcon,
  record_voice_over: MicIcon,
  redeem: GiftIcon,
  refresh: RefreshCwIcon,
  replay: RepeatIcon,
  replay_10: HistoryIcon,
  rocket_launch: RocketIcon,
  route: RouteIcon,
  rubric: ListChecksIcon,
  save: SaveIcon,
  schedule: Clock3Icon,
  school: GraduationCapIcon,
  search: SearchIcon,
  search_off: SearchXIcon,
  self_improvement: BrainIcon,
  send: SendIcon,
  settings: SettingsIcon,
  signpost: RouteIcon,
  skip_next: SkipForwardIcon,
  skip_previous: SkipBackIcon,
  slideshow: LayoutGridIcon,
  smart_toy: BotIcon,
  source: ArchiveIcon,
  space_dashboard: LayoutDashboardIcon,
  star: StarIcon,
  stop: SquareIcon,
  style: BookmarkIcon,
  sync: RefreshCwIcon,
  target: TargetIcon,
  task_alt: CheckCircle2Icon,
  terminal: TerminalIcon,
  textsms: MessageCircleIcon,
  thumb_up: ThumbsUpIcon,
  timer: TimerIcon,
  today: CalendarDaysIcon,
  touch_app: CrosshairIcon,
  trending_up: TrendingUpIcon,
  unfold_more: ChevronUpIcon,
  upload: UploadIcon,
  verified: BadgeCheckIcon,
  verified_user: ShieldCheckIcon,
  vertical_align_center: Maximize2Icon,
  visibility: EyeIcon,
  visibility_off: EyeOffIcon,
  warning: AlertTriangleIcon,
  workspace_premium: TrophyIcon,
};

/**
 * App-wide icon renderer. Accepts legacy Material Symbols names.
 * Use SVG Lucide icons only — no icon fonts.
 */
export default function AppIcon({
  name,
  children,
  className = '',
  size,
  strokeWidth = 1.75,
  'aria-hidden': ariaHidden = true,
  style,
  title,
  ...props
}) {
  const resolvedName = String(name || children || '').trim();
  const Icon = MATERIAL_TO_LUCIDE[resolvedName] || CircleHelpIcon;
  const spin = resolvedName === 'progress_activity' || resolvedName === 'pending';

  return (
    <Icon
      className={cn('inline-block shrink-0 size-[1em]', spin && 'animate-spin', className)}
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden={ariaHidden}
      style={style}
      title={title}
      {...props}
    />
  );
}
