import formsPlugin from '@tailwindcss/forms';
import containerQueriesPlugin from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                /* shadcn-style CSS variable colors for hero components */
                background: 'rgb(var(--background) / <alpha-value>)',
                foreground: 'rgb(var(--foreground) / <alpha-value>)',
                muted: {
                    DEFAULT: 'rgb(var(--border) / <alpha-value>)',
                    foreground: 'rgb(var(--muted-foreground) / <alpha-value>)',
                },
                accent: {
                    DEFAULT: 'rgb(var(--border) / <alpha-value>)',
                    foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
                    teal: '#1de9b6',
                    emerald: '#00c853',
                    amber: '#ffab00',
                    coral: '#ff6d00',
                    purple: '#0D9488',
                    pink: '#f50057',
                },
                border: 'rgb(var(--border) / <alpha-value>)',
                input: 'rgb(var(--input) / <alpha-value>)',
                ring: 'rgb(var(--ring) / <alpha-value>)',
                popover: {
                    DEFAULT: 'rgb(var(--popover) / <alpha-value>)',
                    foreground: 'rgb(var(--popover-foreground) / <alpha-value>)',
                },
                sidebar: {
                    DEFAULT: 'rgb(var(--sidebar) / <alpha-value>)',
                    foreground: 'rgb(var(--sidebar-foreground) / <alpha-value>)',
                    primary: 'rgb(var(--sidebar-primary) / <alpha-value>)',
                    'primary-foreground': 'rgb(var(--sidebar-primary-foreground) / <alpha-value>)',
                    accent: 'rgb(var(--sidebar-accent) / <alpha-value>)',
                    'accent-foreground': 'rgb(var(--sidebar-accent-foreground) / <alpha-value>)',
                    border: 'rgb(var(--sidebar-border) / <alpha-value>)',
                    ring: 'rgb(var(--sidebar-ring) / <alpha-value>)',
                },
                /* Slate redesign: primary = system blue, CTA = near-black pills */
                primary: {
                    DEFAULT: "#007AFF",
                    foreground: "#FFFFFF",
                    hover: "#0066D6",
                    light: "#5AC8FA",
                    dark: "#0040DD",
                    subtle: "#F2F7FF",
                    50: "#F2F7FF",
                    100: "#E5F0FF",
                    200: "#C7DEFF",
                    300: "#94C2FF",
                    400: "#5AC8FA",
                    500: "#007AFF",
                    600: "#0066D6",
                    700: "#0055B3",
                    800: "#0040DD",
                    900: "#003EB3",
                    950: "#002266",
                },
                cta: {
                    DEFAULT: "#111111",
                    foreground: "#FFFFFF",
                    hover: "#000000",
                    soft: "#F2F2F7",
                    subtle: "#F9F9F9",
                },
                secondary: {
                    DEFAULT: "#5AC8FA",
                    foreground: "#0A0A0A",
                    light: "#94C2FF",
                    dark: "#0066D6",
                },
                /* Legacy named variants — keep for existing pages */
                "background-light": "#F9F9F9",
                "background-dark": "#0c0d10",
                surface: {
                    light: "#ffffff",
                    dark: "#161719",
                    elevated: "#1c1d20",
                    hover: "#f4f4f6",
                    "hover-dark": "#212226",
                },
                /* Legacy named variants — keep for existing pages */
                "border-light": "#e4e4e7",
                "border-dark": "#2a2b30",
                "border-subtle": "#E5E5EA",
                "border-subtle-dark": "#202124",
                text: {
                    main: {
                        light: "#0A0A0A",
                        dark: "#e9e9ee",
                    },
                    sub: {
                        light: "#6B6B70",
                        dark: "#a1a1aa",
                    },
                    faint: {
                        light: "#8E8E93",
                        dark: "#a1a1aa",
                    },
                },
                /* ── ChewnPour Slate redesign system ── */
                "text-primary": "#0A0A0A",
                "text-secondary": "#6B6B70",
                "text-muted": "#6B6B70",
                "surface-soft": "#F2F2F7",
                "surface-muted": "#E5E5EA",
                "surface-variant": "#F2F2F7",
                "surface-bright": "#FFFFFF",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#F9F9F9",
                "surface-container": "#F2F2F7",
                "surface-container-high": "#E5E5EA",
                "surface-container-highest": "#D1D1D6",
                "surface-dim": "#E5E5EA",
                "surface-tint": "#007AFF",
                "on-surface": "#0A0A0A",
                "on-surface-variant": "#6B6B70",
                "on-primary": "#ffffff",
                "on-secondary": "#0A0A0A",
                "on-background": "#0A0A0A",
                "border-default": "#E5E5EA",
                "border-strong": "#C7C7CC",
                "outline": "#8E8E93",
                "outline-variant": "#E5E5EA",
                "inverse-surface": "#0A0A0A",
                "inverse-on-surface": "#F9F9F9",
                "inverse-primary": "#94C2FF",
                "primary-soft": "#E5F0FF",
                "primary-subtle": "#F2F7FF",
                "primary-fixed": "#C7DEFF",
                "primary-fixed-dim": "#5AC8FA",
                "primary-container": "#0066D6",
                "primary-hover": "#0066D6",
                "on-primary-fixed": "#001433",
                "on-primary-fixed-variant": "#003EB3",
                "on-primary-container": "#ffffff",
                "secondary-container": "#ff987b",
                "secondary-fixed": "#ffdbd1",
                "secondary-fixed-dim": "#ffb5a0",
                "on-secondary-fixed": "#3b0900",
                "on-secondary-fixed-variant": "#792f1a",
                "on-secondary-container": "#782e19",
                "tertiary": "#006096",
                "tertiary-container": "#007abd",
                "tertiary-fixed": "#cee5ff",
                "tertiary-fixed-dim": "#96ccff",
                "on-tertiary": "#ffffff",
                "on-tertiary-fixed": "#001d32",
                "on-tertiary-fixed-variant": "#004a75",
                "on-tertiary-container": "#fdfcff",
                "success-soft": "#DCFCE7",
                "warning-soft": "#FEF3C7",
                "error-soft": "#FEE2E2",
                "info-soft": "#DBEAFE",
                "mastery-soft": "#E5F0FF",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "ai-soft": "#E5F0FF",
                "ai-subtle": "#F2F7FF",
                "success": "#15803D",
                "warning": "#FF9F0A",
                "error": "#FF3B30",
                "info": "#007AFF",
                "mastery": "#007AFF",
            },
            fontFamily: {
                display: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                body: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                mono: ['"JetBrains Mono"', '"Fira Code"', "monospace"],
                "headline-sm": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "headline-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "body-base": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "body-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "body-sm": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "label-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "label-xs": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "display-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
                "display-xl": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
            },
            fontSize: {
                "display-xl": ["2.75rem", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
                "display-lg": ["2rem", { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" }],
                "display-md": ["1.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
                "display-sm": ["1.25rem", { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "600" }],
                "body-lg": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
                "body-md": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
                "body-sm": ["0.8125rem", { lineHeight: "1.5", fontWeight: "400" }],
                "caption": ["0.75rem", { lineHeight: "1.4", fontWeight: "500" }],
                "overline": ["0.6875rem", { lineHeight: "1.4", letterSpacing: "0.06em", fontWeight: "600" }],
                "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
                "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "1", fontWeight: "600" }],
                "label-xs": ["12px", { lineHeight: "1", fontWeight: "500" }],
            },
            borderRadius: {
                "DEFAULT": "0.5rem",
                "lg": "0.75rem",
                "xl": "1rem",
                "2xl": "1.25rem",
                "3xl": "1.5rem",
                "4xl": "2rem",
                "full": "9999px",
            },
            boxShadow: {
                "xs": "0 1px 2px rgba(0,0,0,0.04)",
                "soft": "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
                "card": "0 1px 3px rgba(0,0,0,0.08), 0 4px 12px rgba(0,0,0,0.04)",
                "card-hover": "0 2px 8px rgba(0,0,0,0.12), 0 8px 24px rgba(0,0,0,0.06)",
                "elevated": "0 4px 16px rgba(0,0,0,0.08), 0 12px 40px rgba(0,0,0,0.04)",
                "modal": "0 8px 32px rgba(0,0,0,0.12), 0 24px 64px rgba(0,0,0,0.08)",
                "glass": "0 0 0 1px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.04)",
                "button": "0 1px 3px rgba(217,119,6,0.28), 0 4px 12px rgba(217,119,6,0.14)",
                "button-hover": "0 2px 6px rgba(217,119,6,0.36), 0 8px 20px rgba(217,119,6,0.18)",
                "inner": "inset 0 1px 2px rgba(0,0,0,0.06)",
                "ring": "0 0 0 3px rgba(13,148,136,0.18)",
            },
            spacing: {
                "4.5": "1.125rem",
                "13": "3.25rem",
                "15": "3.75rem",
                "18": "4.5rem",
                "22": "5.5rem",
                "sidebar": "16.5rem",
                "sidebar-collapsed": "4.5rem",
                "space-1": "4px",
                "space-2": "8px",
                "space-3": "12px",
                "space-4": "16px",
                "space-5": "20px",
                "space-6": "24px",
                "space-8": "32px",
                "space-10": "40px",
                "space-12": "48px",
                "space-16": "64px",
                "sidebar-width": "260px",
                "container-max": "1280px",
                "panel-right-width": "320px",
            },
            animation: {
                "fade-in": "fadeIn 0.4s ease-out forwards",
                "fade-in-up": "fadeInUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
                "slide-up": "slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
                "slide-down": "slideDown 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
                "slide-in-right": "slideInRight 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
                "slide-in-left": "slideInLeft 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
                "scale-in": "scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards",
                "shimmer": "shimmer 2s linear infinite",
                "pulse-gentle": "pulseGentle 2.5s ease-in-out infinite",
                "spin-slow": "spin 3s linear infinite",
                "marquee": "marquee 30s linear infinite",
            },
            keyframes: {
                marquee: {
                    "0%": { transform: "translateX(0)" },
                    "100%": { transform: "translateX(-50%)" },
                },
                fadeIn: {
                    "0%": { opacity: "0" },
                    "100%": { opacity: "1" },
                },
                fadeInUp: {
                    "0%": { opacity: "0", transform: "translateY(12px)" },
                    "100%": { opacity: "1", transform: "translateY(0)" },
                },
                slideUp: {
                    "0%": { opacity: "0", transform: "translateY(16px)" },
                    "100%": { opacity: "1", transform: "translateY(0)" },
                },
                slideDown: {
                    "0%": { opacity: "0", transform: "translateY(-16px)" },
                    "100%": { opacity: "1", transform: "translateY(0)" },
                },
                slideInRight: {
                    "0%": { opacity: "0", transform: "translateX(16px)" },
                    "100%": { opacity: "1", transform: "translateX(0)" },
                },
                slideInLeft: {
                    "0%": { opacity: "0", transform: "translateX(-16px)" },
                    "100%": { opacity: "1", transform: "translateX(0)" },
                },
                scaleIn: {
                    "0%": { opacity: "0", transform: "scale(0.96)" },
                    "100%": { opacity: "1", transform: "scale(1)" },
                },
                shimmer: {
                    "0%": { backgroundPosition: "-200% 0" },
                    "100%": { backgroundPosition: "200% 0" },
                },
                pulseGentle: {
                    "0%, 100%": { opacity: "1" },
                    "50%": { opacity: "0.6" },
                },
            },
            transitionTimingFunction: {
                "spring": "cubic-bezier(0.16, 1, 0.3, 1)",
            },
        },
    },
    plugins: [
        formsPlugin,
        containerQueriesPlugin,
    ],
}
